imports:
    - { resource: parameters.ini }

framework:
    charset:       UTF-8
    error_handler: null
    csrf_protection:
        enabled: true
        secret: %csrf_secret%
    router:        { resource: "%kernel.root_dir%/config/routing.yml" }
    validation:    { enabled: true, annotations: true }
    templating:    { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        lifetime:       3600
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        logging:  %kernel.debug%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        mappings:
    #        FOSUserBundle: ~
    #        LottoLottoBundle:   ~


# Swiftmailer Configuration
swiftmailer:
    transport:  %mailer_transport%
    host:       %mailer_host%
    username:   %mailer_user%
    password:   %mailer_password%

# Security Configuration    
#security:
#    providers:
#        fos_user:
#            id: fos_user.user_manager
#    
#    firewalls:
#        main:
#            form_login:
#                provider: fos_userbundle
#                
#fos_user:
#    db_driver: orm
#    provider_key: fos_userbundle
#    class:
#        model:
#            user: Lotto\LottoBundle\Entity\User
#            group: FOS\UserBundle\Entity\DefaultGroup
            
                



