fos_user_security:
    resource: @FOSUserBundle/Resources/config/routing/security.xml

fos_user_user:
    resource: @FOSUserBundle/Resources/config/routing/user.xml
    prefix: /user

homepage:
    pattern:  /
    defaults: { _controller: LottoLottoBundle:Lotto:index }

lotto:
    resource: @LottoLottoBundle/Resources/config/routing.yml
