#fos_user_security:
#    resource: @FOSUserBundle/Resources/config/routing/security.xml
#
#fos_user_user:
#    resource: @FOSUserBundle/Resources/config/routing/user.xml
#    prefix: /user


security:
    resource: @SecurityUserBundle/Resources/config/routing.yml
